json.id product.id
json.supplier_id product.supplier_id
json.name product.name
json.inventory product.inventory
json.price product.price
json.tax product.tax
json.total product.total
json.is_discounted? product.is_discounted?
json.image_url product.image_url
json.description product.description
json.supplier product.supplier
json.created_at product.created_at
json.updated_at product.updated_at
